# https://taskfile.dev

version: "3"

dotenv: ["bananapi.env"]

vars:
  DOCKER_IMAGE: "crops/poky"
  MACHINE: "bananapi-zero"
  IMAGE_PATH: "build/tmp/deploy/images/{{.MACHINE}}"
  IMAGE: "image"
  MENDER_KEY:
    sh: cat mender.key
  WORKSPACE:
    sh: pwd

tasks:
  default:
    - task: run
  run:
    cmds:
      - |
        docker run --rm \
        -v {{.WORKSPACE }}:{{.WORKSPACE}} \
        -v {{.WORKSPACE }}/downloads:{{.WORKSPACE }}/downloads \
        -v {{.WORKSPACE }}/sstate:{{.WORKSPACE }}/sstate \
        -e WLAN0_SSID=${WLAN0_SSID} \
        -e WLAN0_PSK=${WLAN0_PSK} \
        -e GENERATED_MENDER_KEY="{{.MENDER_KEY}}" \
        -e BB_ENV_PASSTHROUGH_ADDITIONS="WLAN0_SSID WLAN0_PSK GENERATED_MENDER_KEY" \
        -it {{.DOCKER_IMAGE}} /bin/bash -c "cd {{.WORKSPACE}} && source src/poky/oe-init-build-env  && /bin/bash"
  deploy:
    deps: [umount]
    vars:
      DEPLOY_IMAGE: "{{.IMAGE_PATH}}/{{.IMAGE}}-{{.MACHINE}}.sdimg"
    cmds:
      - sudo bmaptool copy {{.DEPLOY_IMAGE}}.bz2 --bmap {{.DEPLOY_IMAGE}}.bmap $DRIVE
  deploy_orange:
    deps: [umount]
    vars:
      IMAGE: "core-image-minimal"
      MACHINE: "orangepi-zero-2w"
      IMAGE_PATH: "build/tmp/deploy/images/{{.MACHINE}}"
      DEPLOY_IMAGE: "{{.IMAGE_PATH}}/{{.IMAGE}}-{{.MACHINE}}.wic"
    cmds:
      - sudo bmaptool copy {{.DEPLOY_IMAGE}}.gz --bmap {{.DEPLOY_IMAGE}}.bmap $DRIVE
  fsck:
    deps: [umount]
    cmds:
      - sudo fsck "$DRIVE"2
      - sudo fsck "$DRIVE"3
      - sudo fsck "$DRIVE"4
  clean:
    cmds:
      - rm -rf build/tmp
  artifact:
    vars:
      VERSION: 0.1.2
    cmds:
      - |
        mender-artifact write rootfs-image \
        -t bananapi-zero \
        -n {{.VERSION}} \
        --software-version {{.VERSION}} \
        -f {{.IMAGE_PATH}}/{{.IMAGE}}-{{.MACHINE}}.ext4 \
        -o {{.VERSION}}.mender
  umount:
    internal: true
    preconditions:
      - sh: '[ "$DRIVE" != "" ]'
        msg: Environment variable DRIVE must be defined
    silent: true
    cmds:
      - |
        sudo umount "$DRIVE"1 || /bin/true 
        sudo umount "$DRIVE"2 || /bin/true 
        sudo umount "$DRIVE"3 || /bin/true 
        sudo umount "$DRIVE"4 || /bin/true
