#!/bin/sh

# This script will be called via mini X session on behalf of the file owner, after
# being installed in /etc/mini_x/session.d/.

xset s off  > /dev/null 2>&1        # don't activate screensaver
xset -dpms   > /dev/null 2>&1       # disable DPMS (Energy Star) features.
xset s noblank   > /dev/null 2>&1   # don't blank the video device

# Set a resolution
xrandr -s 1024x600

matchbox-terminal&
# Run the wm first
matchbox-window-manager -use_titlebar no -use_cursor no &

su -l -c "/usr/bin/gui" root